<?php
$data = array(
  27 =>
  array(
    'cat_id' => '27',
    'cat_name' => '富硒粮米',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '27',
    'name' => '富硒粮米',
  ),
  28 =>
  array(
    'cat_id' => '28',
    'cat_name' => '富硒杂粮',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '28',
    'name' => '富硒杂粮',
  ),
  29 =>
  array(
    'cat_id' => '29',
    'cat_name' => '富硒有机粮',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '29',
    'name' => '富硒有机粮',
  ),
  24 =>
  array(
    'cat_id' => '24',
    'cat_name' => '富硒果蔬',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '24',
    'name' => '富硒果蔬',
  ),
  30 =>
  array(
    'cat_id' => '30',
    'cat_name' => '富硒水果',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '30',
    'name' => '富硒水果',
  ),
  31 =>
  array(
    'cat_id' => '31',
    'cat_name' => '富硒绿色蔬菜',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '31',
    'name' => '富硒绿色蔬菜',
  ),
  25 =>
  array(
    'cat_id' => '25',
    'cat_name' => '生物有机肥',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '生物有机肥',
  ),
  32 =>
  array(
    'cat_id' => '32',
    'cat_name' => '有机富钾肥',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '32',
    'name' => '有机富钾肥',
  ),
  33 =>
  array(
    'cat_id' => '33',
    'cat_name' => '生物符合肥料',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '33',
    'name' => '生物符合肥料',
  ),
  34 =>
  array(
    'cat_id' => '34',
    'cat_name' => '富硒肥料',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '34',
    'name' => '富硒肥料',
  ),
  4 =>
  array(
    'cat_id' => '4',
    'cat_name' => '硒健营养',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '硒健营养',
  ),
  20 =>
  array(
    'cat_id' => '20',
    'cat_name' => '药食同源',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '20',
    'name' => '药食同源',
  ),
  21 =>
  array(
    'cat_id' => '21',
    'cat_name' => '膳食补充剂',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '21',
    'name' => '膳食补充剂',
  ),
  19 =>
  array(
    'cat_id' => '19',
    'cat_name' => '传统滋补',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '传统滋补',
  ),
  1 =>
  array(
    'cat_id' => '1',
    'cat_name' => '硒茶冲饮',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '硒茶冲饮',
  ),
  8 =>
  array(
    'cat_id' => '8',
    'cat_name' => '绞股蓝',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '8',
    'name' => '绞股蓝',
  ),
  5 =>
  array(
    'cat_id' => '5',
    'cat_name' => '富硒藤茶',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '5',
    'name' => '富硒藤茶',
  ),
  9 =>
  array(
    'cat_id' => '9',
    'cat_name' => '富硒饮品',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '9',
    'name' => '富硒饮品',
  ),
  6 =>
  array(
    'cat_id' => '6',
    'cat_name' => '富硒绿茶',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '6',
    'name' => '富硒绿茶',
  ),
  7 =>
  array(
    'cat_id' => '7',
    'cat_name' => '花草茶',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '7',
    'name' => '花草茶',
  ),
  2 =>
  array(
    'cat_id' => '2',
    'cat_name' => '硒米粮油植物油',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '硒米粮油植物油',
  ),
  11 =>
  array(
    'cat_id' => '11',
    'cat_name' => '富硒大米',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '11',
    'name' => '富硒大米',
  ),
  12 =>
  array(
    'cat_id' => '12',
    'cat_name' => '富硒杂粮',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '12',
    'name' => '富硒杂粮',
  ),
  13 =>
  array(
    'cat_id' => '13',
    'cat_name' => '有机杂粮',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '13',
    'name' => '有机杂粮',
  ),
  10 =>
  array(
    'cat_id' => '10',
    'cat_name' => '植物油',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '10',
    'name' => '植物油',
  ),
  26 =>
  array(
    'cat_id' => '26',
    'cat_name' => '其他精品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '26',
    'name' => '其他精品',
  ),
  3 =>
  array(
    'cat_id' => '3',
    'cat_name' => '硒特优品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '硒特优品',
  ),
  17 =>
  array(
    'cat_id' => '17',
    'cat_name' => '肉制腊货',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '17',
    'name' => '肉制腊货',
  ),
  14 =>
  array(
    'cat_id' => '14',
    'cat_name' => '食用菌类',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '14',
    'name' => '食用菌类',
  ),
  18 =>
  array(
    'cat_id' => '18',
    'cat_name' => '地标产品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '18',
    'name' => '地标产品',
  ),
  15 =>
  array(
    'cat_id' => '15',
    'cat_name' => '休闲零食',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '15',
    'name' => '休闲零食',
  ),
  16 =>
  array(
    'cat_id' => '16',
    'cat_name' => '生鲜果蔬',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '生鲜果蔬',
  ),
);
